//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowBisaoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resposta
    {
        public int IdAlternativa { get; set; }
        public int Rodada { get; set; }
        public string Alternativa { get; set; }
        public Nullable<bool> EhCorreta { get; set; }
        public int IdPergunta { get; set; }
    
        public virtual Pergunta Pergunta { get; set; }
    }
}
